-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Church.

module Church.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Church.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Church.Abs.VarId where
  prt _ (Church.Abs.VarId i) = doc $ showString i
instance Print Church.Abs.Term where
  prt i = \case
    Church.Abs.Var varid -> prPrec i 0 (concatD [prt 0 varid])
    Church.Abs.App term1 term2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 term1, prt 0 term2, doc (showString ")")])
    Church.Abs.Abs varid type_ term -> prPrec i 0 (concatD [doc (showString "\\"), prt 0 varid, doc (showString ":"), prt 0 type_, doc (showString "."), prt 0 term])
    Church.Abs.Pair term1 term2 -> prPrec i 0 (concatD [doc (showString "{"), prt 0 term1, doc (showString ","), prt 0 term2, doc (showString "}")])
    Church.Abs.Fst term -> prPrec i 0 (concatD [doc (showString "fst"), prt 0 term])
    Church.Abs.Snd term -> prPrec i 0 (concatD [doc (showString "snd"), prt 0 term])
    Church.Abs.Inl term type_ -> prPrec i 0 (concatD [doc (showString "inl"), prt 0 term, doc (showString "as"), prt 0 type_])
    Church.Abs.Inr term type_ -> prPrec i 0 (concatD [doc (showString "inr"), prt 0 term, doc (showString "as"), prt 0 type_])
    Church.Abs.Case term1 term2 term3 -> prPrec i 0 (concatD [doc (showString "case"), prt 0 term1, doc (showString "of"), prt 0 term2, doc (showString "|"), prt 0 term3])
    Church.Abs.Abort term type_ -> prPrec i 0 (concatD [doc (showString "abort"), prt 0 term, prt 0 type_])

instance Print Church.Abs.Type where
  prt i = \case
    Church.Abs.A -> prPrec i 0 (concatD [doc (showString "A")])
    Church.Abs.B -> prPrec i 0 (concatD [doc (showString "B")])
    Church.Abs.C -> prPrec i 0 (concatD [doc (showString "C")])
    Church.Abs.D -> prPrec i 0 (concatD [doc (showString "D")])
    Church.Abs.Bot -> prPrec i 0 (concatD [doc (showString "Bot")])
    Church.Abs.Func type_1 type_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_1, doc (showString "->"), prt 0 type_2, doc (showString ")")])
    Church.Abs.Sum type_1 type_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_1, doc (showString "+"), prt 0 type_2, doc (showString ")")])
    Church.Abs.Prod type_1 type_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_1, doc (showString "*"), prt 0 type_2, doc (showString ")")])
