-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Curry.

module Curry.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Term
    = Var Variable
    | App Term Term
    | Abs Variable Term
    | Pair Term Term
    | Fst Term
    | Snd Term
    | Inl Term
    | Inr Term
    | Case Term Term Term
    | Abrt Term
    | T
    | F
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Variable = Variable String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

